- dash.el
Copyright replacement for existing code.
> Reimplementation of --group-by.

- dash-functional.el
- dash.el
- dash.texi
Update the copyright lines following copyright assignment policy.
> Add support for GNU ELPA.

- README.md
- readme-template.md
Hey guys.
Probably ill-advised on my part but I changed my GitHub username so if it's not too much trouble here's a PR to update the contributors section of the README
> Fix broken GH profile link in README

- README.md
- readme-template.md
New features/bugfixes are shown chronologically.
Requested in #190.
> Update changelog for 2.12.x.

- README.md
- dash.el
This is a copy-paste typo, right?
> Fix -map-last docs

- README.md
- dash.info
- dash.texi
- dev/examples.el
> Docs: Clarify that we don't modify the original list

- README.md
- dash.el
- dash.info
- dash.texi
- dev/examples.el
* Fixes #239 
* Extend examples accordingly
* Update docs
> Replace -first with -some in -any?

- dev/examples-to-docs.el
- dev/examples-to-info.el
This enables us to generate docs on newer (25+) Emacsen.
Fixes #192.
> Set text-quoting-style

- dash.info
I've noticed that the info manual was outdated, so I've regenerated it.
> Regenerate docs

- README.md
- dash.el
- dash.info
- dash.texi
- dev/examples.el
> Implement -setq

- README.md
- dash.el
- dash.info
- dash.texi
- dev/examples.el
> Smart kv destructuring

- README.md
- dash.el
- dash.info
- dash.texi
- dev/examples.el
- readme-template.md
> Doublep each r

- dash.el
- dev/examples.el
Update `-common-prefix` tests along with those of `-common-suffix`.
Re: #262 
Moral question: Is it worth adding this function when users bent on bad practice like this can write the code themselves?
> Add -common-suffix

- dash.el
- dev/examples.el
Please let me know if you want me regenerate the docs. When I ran
./create-docs.sh it generates a lot of changes not related to this PR.
> Implement --doto

- dash.el
- dev/examples.el
Close https://github.com/magnars/dash.el/issues/294
> Ensure `hash?` expander evaluates its arg only once.

- README.md
It has been dead for a while now.
> Remove mention of Marmalade

- dash.el
> Make -inits not destroy its argument

- dash.el
> Clarify docs on -zip-pair future behaviour

- pre-commit.sh
> use bash for pre-commit script

- .dir-locals.el
> Add dir-locals-file with useful settings

- dash.el
- dev/examples.el
> Add -iota (#207)

- README.md
- dash.el
- dash.texi
Hola! 👋 
Not sure if interested in something so small, but was a tiny typo if you want a fix.
> Fix typo in --> docstring in dash.el
